### PR TITLE
address: Add geo(graphy) type (country) with example

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by hlroudjehane** [comment]
Here is the error I was receiving after updating code.

image

**Comment by alagoutte** [comment]
can you try

```powershell
Add-FGTFirewallAddress -name FGT-Country-FI -country FI 
```
?

(Remove the extra Finland... or remove extra FGT-Country-FI ;-) and kept only finland =)

and use
```powershell
Import-Module PowerFGT -Force
```

**Comment by hlroudjehane** [comment]
Could you entertain a few questions for me please?

Is this an HTTP API?
If so where did you learn how to build HTTP API’s
If not what type of API is it and where did you learn to build it?

I appreciate your answers!

From: Redouane Oudjehane
Sent: Thursday, June 30, 2022 12:40 PM
To: FortiPower/PowerFGT ***@***.***>; FortiPower/PowerFGT ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [FortiPower/PowerFGT] address: Add geo(graphy) type (country) with example (PR #191)

So my issue was that I created a new address.ps1 file and pasted the new code in there because I was getting permission denied when updated your original file. I found a way to update the code in there and save successfully. Odd though that a new file named address.ps1 didn’t work even though I renamed the old file address_old.ps1.

It ended up working though so thank you so much for your quick response and help with updating the API!

**Comment by alagoutte** [comment]
> Could you entertain a few questions for me please? Is this an HTTP API? If so where did you learn how to build HTTP API’s If not what type of API is it and where did you learn to build it? I appreciate your answers!

Yes, it is a HTTP API, you can search on Google a PDF FOS REST API reference for help to understand API or you can also look the code of this module ([Connection.ps1](https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/Connection.ps1) and [RestMethod.ps1](https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Private/RestMethod.ps1)), there is also [FNDN](https://fndn.fortinet.net) (but need an account validated by Fortinet...)

**Comment by hlroudjehane** [comment]
So my issue was that I created a new address.ps1 file and pasted the new code in there because I was getting permission denied when updated your original file. I found a way to update the code in there and save successfully. Odd though that a new file named address.ps1 didn’t work even though I renamed the old file address_old.ps1.

It ended up working though so thank you so much for your quick response and help with updating the API!

**Comment by alagoutte** [comment]
> So my issue was that I created a new address.ps1 file and pasted the new code in there because I was getting permission denied when updated your original file. I found a way to update the code in there and save successfully. Odd though that a new file named address.ps1 didn’t work even though I renamed the old file address_old.ps1. It ended up working though so thank you so much for your quick response and help with updating the API!

Thanks for feedback !

Sorry for delay, but the new release will be available on next month (not yet ETA...)

**Pull request merged**
