### PR TITLE
Added an example on FGT backup using the Invoke-FGTRestMethod 

### PR DESCRIPTION
**Pull request by poundy**
I went looking to see how to do the backup and struggled a bit and once I found it I thought I'd do the community thing and do a PR for it

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi,

it will be better to add Get cmdlet (Like Get-FGTMonitoringSystemConfigBackup) with parameter to select scope (and may be other option)

**Comment by poundy** [comment]
I agree that it'd be great to add a new capability to the queue, but in the meantime a simple example can help, which is why the PR.

**Comment by alagoutte** [comment]
it is very easy to add directly the new cmdlet (Invoke-FGTRestMethod don't really need to be used by user... it is a internal function

**Comment by poundy** [comment]
but..... you pointed me to it before ! ;-)

Plus, really, there's 8 example calls in the document anyway, what's a 9th?

**Comment by alagoutte** [comment]
if you look it is all the same URI for example, it is only to have example with different option parameter

(and also this file is auto-generated... need to update the source code)
it will look for add this get

**Comment by poundy** [comment]
Revert this

**Pull request closed without merging**
